### ISSUE TITLE
`---` h1 syntax not compatible with parser

### ISSUE THREAD

**Issue by ktravers** [learn-co-curriculum/javascript-comments#6]
@pletcher i believe the `---` syntax for defining an h1 is causing problems with our MarkdownToHtml parser. currently, the parser removes the lesson title by gsubbing out the first `#` header it finds. since most of the js labs use the `---` syntax for their titles, the wrong header is getting removed. for example, on this lab, it's removing "Objectives" but leaving the title "JavaScript Comments".

<img width="904" alt="screen shot 2016-07-03 at 7 52 17 pm" src="https://cloud.githubusercontent.com/assets/8152930/16548298/016c8090-4158-11e6-8975-dc6ebfcbeded.png">

until we modify the parser, i would strongly suggest using the standard `#` syntax for lesson title headers. if you use the `learn-co` gem command [`learn new <template name>`](https://github.com/learn-co/learn-generate), it'll take of this for you.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
That's fine. The learn-co gem's JavaScript lab templates aren't up to date
-- they're using headless browsers that don't support ES6, for one.

I'll update the generator that I've been using.

**Comment by pletcher** [comment]
Fixed :) https://github.com/pletcher/generator-learn/commit/a660d3ba369e452ba334388fbbba07b29a96d102
