### ISSUE TITLE
For the "COMMENT BLOCK SYNTAX: /**/" section, it's unclear that how to do multi-line in console

### ISSUE THREAD

**Issue by abhishekpillai** [learn-co-curriculum/javascript-comments#9]
So, when the curriculum asks us to..
_Enter the following in console:_

```

/*
 I'm a comment, because I'm inside `/*`.
 Still a comment.
 Let's end this comment at the end of this line */

 No longer a comment!
```

It's not obvious that you get to next line by doing shift+enter

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
